/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props:any) {
  const groupRef = useRef()
  const {nodes} = useGLTF('./eldorgltf.gltf') as any

  return (
    <group ref={groupRef} {...props} dispose={null}>
      {/* <primitive scale={[0.12, 0.12, 0.12]} object={gltf.scene} /> */}
      <mesh geometry={nodes.Curve.geometry}>
      <meshStandardMaterial color="#673ab7" roughness={0} metalness={.8} />
    </mesh>
    </group>
  )
}

useGLTF.preload('./eldorgltf.gltf')